import { ArrowLeft, Bookmark, Building2, CheckCircle2, Copy, Globe, IdCard, Mail, MoreHorizontal, Phone, Printer, Send } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const contactRows = [{Icon: Phone,value:'03-9876-5432'},{Icon: Printer,value:'03-9876-5433'},{Icon: Globe,value:'tohto-realty.jp'},{Icon: Mail,value:'sato@tohto-realty.jp'}];

export default function DesignChat() {
  const [, setLocation] = useLocation();
  const [modal, setModal] = useState<null | 'share' | 'contact'>(null);
  const [flagged, setFlagged] = useState(false);
  const [includeCard, setIncludeCard] = useState(false);
  const [includeProperty, setIncludeProperty] = useState(true);

  return <div className="flex min-h-screen flex-col bg-[#edf2f7] text-[#17211d]">
    <header className="sticky top-0 z-30 bg-[#173f70] text-white">
      <div className="flex h-14 items-center px-3"><button onClick={() => setLocation('/design/messages')} className="grid size-10 place-items-center"><ArrowLeft size={21} /></button><div className="ml-1 min-w-0"><div className="flex items-center gap-1.5"><h1 className="truncate text-[16px] font-bold">佐藤 健一</h1><span className="flex items-center gap-0.5 bg-white/15 px-1.5 py-0.5 text-[9px] font-bold"><CheckCircle2 size={10} />認証済み</span></div><p className="truncate text-[10px] text-white/65">東都リアルティ株式会社</p></div><button className="ml-auto grid size-10 place-items-center"><MoreHorizontal size={21} /></button></div>
      <button onClick={() => setLocation('/design/property')} className="flex w-full items-center border-t border-white/15 bg-[#12345e] px-4 py-3 text-left"><div className="grid size-9 place-items-center bg-white/10"><Building2 size={18} /></div><div className="ml-3 min-w-0"><div className="flex items-center gap-2"><p className="truncate text-[13px] font-bold">代沢レジデンス</p><span className="bg-white/15 px-1.5 py-0.5 text-[9px] font-bold">問い合わせあり</span></div><p className="text-[11px] text-white/65">1億8,500万円・一棟マンション</p></div><span className="ml-auto text-[11px] text-white/65">詳細を見る</span></button>
    </header>

    <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-5">
      <div className="mb-4 flex items-center gap-2 overflow-x-auto [scrollbar-width:none]"><button onClick={() => setModal('share')} className="flex shrink-0 items-center gap-1.5 border border-[#a9b8c8] bg-white px-3 py-2 text-[12px] font-bold text-[#173f70]"><IdCard size={15} />連絡先を送る</button><button onClick={() => setModal('contact')} className="flex shrink-0 items-center gap-1.5 border border-[#a9b8c8] bg-white px-3 py-2 text-[12px] font-bold text-[#173f70]"><IdCard size={15} />相手の連絡先</button><button onClick={() => setFlagged(!flagged)} className={`ml-auto flex shrink-0 items-center gap-1.5 border px-3 py-2 text-[12px] font-bold ${flagged ? 'border-[#d5ad54] bg-[#fff0c9] text-[#8b5a08]' : 'border-[#a9b8c8] bg-white text-[#65748a]'}`}><Bookmark size={15} fill={flagged ? 'currentColor' : 'none'} />{flagged ? '要返信中' : '要返信'}</button></div>

      <div className="space-y-5"><p className="text-center text-[11px] text-[#7b8797]">8月20日</p><div className="max-w-[82%]"><div className="bg-white px-4 py-3 text-[14px] leading-6 shadow-sm">お問い合わせありがとうございます。こちらの物件について、ご質問をお送りください。</div><p className="mt-1 text-[10px] text-[#8793a2]">10:14</p></div><div className="ml-auto max-w-[82%]"><div className="bg-[#dce9f7] px-4 py-3 text-[14px] leading-6 text-[#17344f]">接道状況と引渡し時期について確認させてください。</div><p className="mt-1 text-right text-[10px] text-[#8793a2]">10:22</p></div><div className="max-w-[82%]"><div className="bg-white px-4 py-3 text-[14px] leading-6 shadow-sm">南西側の公道に接道しています。引渡し時期は売主様と調整可能です。</div><p className="mt-1 text-[10px] text-[#8793a2]">10:31</p></div><div className="max-w-[82%]"><div className="border border-[#ccd7e2] bg-white px-4 py-3 text-[13px] text-[#526176]"><div className="flex items-center gap-2"><Mail size={17} className="text-[#173f70]" /><span className="font-bold">名刺付き情報メールを送りました</span></div><p className="mt-1 text-[11px] text-[#7b8797]">名刺画像はメールをご確認ください</p></div><p className="mt-1 text-[10px] text-[#8793a2]">10:42</p></div></div>
    </main>

    <footer className="sticky bottom-0 border-t border-[#d6dee7] bg-white px-3 py-2 pb-[max(10px,env(safe-area-inset-bottom))]"><div className="mx-auto flex max-w-3xl items-end gap-2"><textarea rows={1} placeholder="メッセージを入力..." className="min-h-11 flex-1 resize-none rounded-[22px] border border-[#cbd5df] bg-[#f8fafc] px-4 py-2.5 text-[14px] outline-none focus:border-[#173f70]" /><button className="grid size-11 shrink-0 place-items-center rounded-full bg-[#173f70] text-white"><Send size={19} /></button></div></footer>

    {modal === 'share' && <div className="fixed inset-0 z-50 flex items-end bg-black/45" onClick={() => setModal(null)}><div className="w-full bg-white p-5" onClick={e => e.stopPropagation()}><h2 className="flex items-center gap-2 text-[18px] font-bold text-[#102d50]"><IdCard size={20} />連絡先を送る</h2><p className="mt-3 text-[13px] leading-6 text-[#526176]">自分の電話番号・FAX・URL・メールアドレスを、このDMの相手に共有します。</p><label className="mt-4 flex items-start border-t border-[#e1e6ec] pt-4 text-[13px] font-semibold"><input type="checkbox" checked={includeCard} onChange={e => setIncludeCard(e.target.checked)} className="mr-3 mt-0.5 size-4" /><span>名刺も合わせて送る<span className="mt-1 block text-[11px] font-normal text-[#758194]">登録済みの名刺画像を相手のメールへ送信します</span></span></label>{includeCard && <label className="ml-7 mt-3 flex items-start text-[12px] font-semibold"><input type="checkbox" checked={includeProperty} onChange={e => setIncludeProperty(e.target.checked)} className="mr-2 mt-0.5" />物件資料リンクもメールに含める</label>}<div className="mt-5 flex gap-3"><button onClick={() => setModal(null)} className="h-11 flex-1 border border-[#173f70] text-[13px] font-bold text-[#173f70]">キャンセル</button><button onClick={() => setModal(null)} className="h-11 flex-1 bg-[#173f70] text-[13px] font-bold text-white">送る</button></div></div></div>}

    {modal === 'contact' && <div className="fixed inset-0 z-50 flex items-end bg-black/45" onClick={() => setModal(null)}><div className="w-full bg-white p-5" onClick={e => e.stopPropagation()}><h2 className="flex items-center gap-2 text-[18px] font-bold text-[#102d50]"><IdCard size={20} />佐藤さんの連絡先</h2><p className="mt-1 text-[12px] font-semibold text-[#65748a]">東都リアルティ株式会社</p><div className="mt-4 border-t border-[#e1e6ec]">{contactRows.map(({Icon,value}) => <div key={value} className="flex items-center border-b border-[#e1e6ec] py-3"><Icon size={17} className="text-[#65748a]" /><span className="ml-3 text-[13px] font-semibold">{value}</span><button className="ml-auto"><Copy size={15} className="text-[#173f70]" /></button></div>)}</div><button onClick={() => setModal(null)} className="mt-5 h-11 w-full bg-[#173f70] text-[13px] font-bold text-white">閉じる</button></div></div>}
  </div>;
}
