import { ArrowLeft, Bell, Building2, ChevronRight, Download, Globe, Heart, HelpCircle, KeyRound, LogOut, MessageCircle, Phone, Smartphone, UserRound } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";
import DesignBottomNav from "@/components/DesignBottomNav";

const companyRows = [{Icon: Building2,label:'会社名',value:'山田不動産株式会社'},{Icon: Phone,label:'電話番号',value:'03-1234-5678'},{Icon: Globe,label:'会社URL',value:'yamada-estate.jp'}];
const menuRows = [{Icon: Heart,label:'お気に入り',path:'/v2/preview/favorites'},{Icon: Building2,label:'自社物件',path:'/v2/preview/my-properties'},{Icon: UserRound,label:'興味者リスト',path:'/v2/preview/interested'},{Icon: Download,label:'ダウンロード資料',path:'/v2/preview/documents'},{Icon: Bell,label:'お知らせ',path:'/v2/preview/announcements'},{Icon: Smartphone,label:'ホーム画面に追加',path:''},{Icon: MessageCircle,label:'LINE連携',path:''},{Icon: KeyRound,label:'パスワード変更',path:''},{Icon: HelpCircle,label:'できること',path:'/v2/preview/features'},{Icon: HelpCircle,label:'管理者へ連絡',path:''}];

export default function DesignMyPage() { const [, setLocation] = useLocation(); const [dialog,setDialog]=useState<string|null>(null); return <div className="min-h-screen bg-[#f2f5f8] pb-20 text-[#17211d]">
  <header className="sticky top-0 z-30 flex h-14 items-center border-b border-[#d9e0e8] bg-white px-3"><button onClick={() => setLocation('/design')} className="grid size-10 place-items-center"><ArrowLeft size={21} /></button><h1 className="ml-1 text-[19px] font-bold text-[#102d50]">マイページ</h1></header>
  <main className="mx-auto max-w-[1200px] space-y-2 lg:grid lg:grid-cols-2 lg:items-start lg:gap-5 lg:space-y-0 lg:px-7 lg:py-7">
    <section className="bg-[#173f70] px-4 py-6 text-white lg:col-span-2 lg:px-7 lg:py-7"><div className="flex items-center"><div className="grid size-16 place-items-center rounded-full bg-white/15 text-[20px] font-bold lg:size-20 lg:text-[24px]">山</div><div className="ml-4 lg:ml-5"><h2 className="text-[20px] font-bold lg:text-[24px]">山田 太郎</h2><p className="mt-1 text-[13px] text-white/70 lg:text-[15px]">山田不動産株式会社</p><p className="mt-0.5 text-[11px] text-white/55 lg:text-[13px]">taro@yamada-estate.jp</p></div><button className="ml-auto border border-white/50 px-3 py-2 text-[11px] font-bold lg:px-5 lg:text-[13px]">編集</button></div></section>
    <section className="bg-white px-4 py-5"><h3 className="text-[15px] font-bold text-[#102d50]">会社情報</h3><dl className="mt-3 border-t border-[#e1e6ec] text-[13px]">{companyRows.map(({Icon,label,value}) => <div key={label} className="flex items-center border-b border-[#e1e6ec] py-3"><Icon size={18} className="text-[#173f70]" /><div className="ml-3"><dt className="text-[10px] text-[#7b8797]">{label}</dt><dd className="mt-0.5 font-semibold">{value}</dd></div><ChevronRight size={16} className="ml-auto text-[#9ca8b7]" /></div>)}</dl></section>
    <section className="bg-white px-4 py-5"><h3 className="text-[15px] font-bold text-[#102d50]">通知設定</h3>{['新着物件のお知らせ','DMの受信通知','物件のお知らせ'].map((x,i) => <label key={x} className="flex items-center border-b border-[#e1e6ec] py-3.5 text-[13px] font-semibold"><Bell size={17} className="mr-3 text-[#173f70]" />{x}<span className={`ml-auto h-6 w-11 rounded-full p-0.5 ${i < 2 ? 'bg-[#173f70]' : 'bg-[#cbd3dc]'}`}><span className={`block size-5 rounded-full bg-white transition ${i < 2 ? 'ml-5' : ''}`} /></span></label>)}</section>
    <section className="bg-white px-4 py-2 lg:col-span-2 lg:grid lg:grid-cols-2 lg:gap-x-8 lg:px-6">{menuRows.map(({Icon,label,path}) => <button key={label} onClick={() => path ? setLocation(path) : setDialog(label)} className="flex w-full items-center border-b border-[#e1e6ec] py-4 text-left"><Icon size={19} className="text-[#173f70]" /><span className="ml-3 text-[14px] font-bold lg:text-[15px]">{label}</span><ChevronRight size={17} className="ml-auto text-[#9ca8b7]" /></button>)}</section>
    <section className="bg-white px-4 py-3 lg:col-span-2 lg:px-6"><button className="flex w-full items-center py-2 text-[14px] font-bold text-[#a72e2e]"><LogOut size={19} className="mr-3" />ログアウト</button></section>
  </main>{dialog&&<div className="fixed inset-0 z-50 flex items-end bg-black/45" onClick={()=>setDialog(null)}><div className="w-full bg-white p-5" onClick={e=>e.stopPropagation()}><h2 className="text-[19px] font-bold text-[#102d50]">{dialog}</h2><p className="mt-2 text-[13px] leading-6 text-[#65748a]">{dialog==='LINE連携'?'公式LINEを友だち追加すると、新着物件をLINEで受け取れます。':dialog==='ホーム画面に追加'?'ブラウザの共有メニューから「ホーム画面に追加」を選択してください。':dialog==='パスワード変更'?'現在のパスワードと新しいパスワードを入力します。':'運営へのお問い合わせ内容を入力してください。'}</p>{dialog==='パスワード変更'&&<div className="mt-4 space-y-2"><input type="password" placeholder="現在のパスワード" className="h-11 w-full border border-[#cbd5df] px-3"/><input type="password" placeholder="新しいパスワード" className="h-11 w-full border border-[#cbd5df] px-3"/></div>}{dialog==='管理者へ連絡'&&<textarea rows={4} className="mt-4 w-full border border-[#cbd5df] p-3" placeholder="お問い合わせ内容"/>}<button onClick={()=>setDialog(null)} className="mt-5 h-11 w-full bg-[#173f70] text-[13px] font-bold text-white">{dialog==='LINE連携'?'友だち追加する':dialog==='パスワード変更'?'変更する':'閉じる'}</button></div></div>}<DesignBottomNav active="mypage" />
</div>; }
