import { ArrowLeft, Download } from "lucide-react";
import { useLocation } from "wouter";

const costs = [
  ['土地代金','185,000,000'], ['建築費','3,500,000'], ['立ち退き料','0'], ['設計','0'],
  ['地盤改良','0'], ['ガス・水道','0'], ['不動産取得税','2,800,000'], ['登記料','1,200,000'],
  ['仲介手数料（買）','6,171,000'], ['仲介手数料（売）','7,284,000'], ['保険','0'], ['解体','0'],
  ['土地測量','0'], ['建物滅失','0'], ['事務手数料','500,000'], ['利息','0'],
];

export default function DesignSimulation() {
  const [, setLocation] = useLocation();
  return <div className="min-h-screen bg-[#f2f5f8] pb-24 text-[#17211d]">
    <header className="sticky top-0 z-30 flex h-14 items-center border-b border-[#d9e0e8] bg-white px-3"><button onClick={() => setLocation('/design/property')} className="grid size-10 place-items-center"><ArrowLeft size={21} /></button><h1 className="ml-1 text-[18px] font-bold text-[#102d50]">利益シミュレーション</h1></header>
    <main className="mx-auto max-w-3xl space-y-2">
      <section className="bg-[#173f70] px-4 py-5 text-white"><p className="text-[11px] text-white/65">対象物件</p><h2 className="mt-1 text-[18px] font-bold">代沢レジデンス</h2><p className="mt-1 text-[12px] text-white/70">東京都世田谷区代沢5丁目18番12号</p></section>
      <section className="bg-white px-4 py-5"><div className="flex items-end justify-between"><h3 className="text-[16px] font-bold text-[#102d50]">原価明細</h3><span className="text-[11px] text-[#758194]">16項目</span></div><div className="mt-3 border-t border-[#dce3eb]">{costs.map(([label,value]) => <label key={label} className="flex items-center border-b border-[#e2e7ec] py-2.5"><span className="flex-1 text-[12px] font-semibold text-[#526176]">{label}</span><input defaultValue={value === '0' ? '' : value} placeholder="0" inputMode="numeric" className="h-9 w-36 border border-[#cbd5df] px-2 text-right text-[13px] font-semibold" /><span className="ml-2 text-[11px]">円</span></label>)}</div><div className="mt-3 flex items-center bg-[#edf3f9] px-3 py-3"><span className="text-[13px] font-bold text-[#173f70]">原価合計</span><span className="ml-auto text-[17px] font-bold text-[#102d50]">206,455,000円</span></div><p className="mt-2 text-[10px] text-[#758194]">各計算結果は1,000円単位で切り上げ</p></section>
      <section className="bg-white px-4 py-5"><h3 className="text-[16px] font-bold text-[#102d50]">仲介手数料の設定</h3><div className="mt-3 space-y-3 text-[12px]"><div className="border border-[#dce3eb] p-3"><p className="font-bold">仲介手数料（買）</p><p className="mt-1 text-[#65748a]">（土地代金 × 3% ＋ 60,000円）× 消費税10%</p><p className="mt-2 text-right text-[14px] font-bold">6,171,000円</p></div><div className="border border-[#dce3eb] p-3"><p className="font-bold">仲介手数料（売）</p><p className="mt-1 text-[#65748a]">（売買価格 × 3% ＋ 0円）× 消費税10%</p><p className="mt-2 text-right text-[14px] font-bold">7,284,000円</p></div></div></section>
      <section className="bg-white px-4 py-5"><h3 className="text-[16px] font-bold text-[#102d50]">売買価格</h3><div className="mt-3 grid grid-cols-2 gap-3"><label><span className="text-[11px] font-semibold text-[#65748a]">1坪あたり単価</span><div className="mt-1 flex items-center"><input defaultValue="4,000,000" className="h-10 min-w-0 flex-1 border border-[#9aabc0] px-2 text-right text-[13px] font-bold" /><span className="ml-1 text-[10px]">円</span></div></label><label><span className="text-[11px] font-semibold text-[#65748a]">坪数</span><div className="mt-1 flex items-center"><input defaultValue="55.18" className="h-10 min-w-0 flex-1 border border-[#9aabc0] px-2 text-right text-[13px] font-bold" /><span className="ml-1 text-[10px]">坪</span></div></label></div><div className="mt-4 flex items-center bg-[#edf3f9] px-3 py-3"><span className="text-[13px] font-bold text-[#173f70]">売買価格</span><span className="ml-auto text-[17px] font-bold text-[#102d50]">220,720,000円</span></div></section>
      <section className="bg-white px-4 py-5"><h3 className="text-[16px] font-bold text-[#102d50]">試算結果</h3><div className="mt-4 space-y-3"><div className="flex justify-between text-[13px]"><span className="text-[#65748a]">原価合計</span><strong>206,455,000円</strong></div><div className="flex justify-between text-[13px]"><span className="text-[#65748a]">売買価格</span><strong>220,720,000円</strong></div><div className="border-t border-[#dce3eb] pt-3"><div className="flex justify-between"><span className="text-[15px] font-bold">利益</span><strong className="text-[21px] text-[#245f9d]">+14,265,000円</strong></div><div className="mt-2 flex justify-between"><span className="text-[15px] font-bold">利益率</span><strong className="text-[21px] text-[#245f9d]">6.5%</strong></div></div></div></section>
    </main>
    <footer className="fixed inset-x-0 bottom-0 border-t border-[#d8e0e8] bg-white p-3"><div className="mx-auto flex max-w-3xl gap-3"><button className="flex h-12 flex-1 items-center justify-center gap-2 border border-[#173f70] text-[13px] font-bold text-[#173f70]"><Download size={17} />PDF保存</button><button className="h-12 flex-[1.4] bg-[#173f70] text-[14px] font-bold text-white">試算を更新</button></div></footer>
  </div>;
}
