import { ArrowLeft, Bell, Camera, Check, Eye, EyeOff, FileText, HelpCircle, Lock, Plus, Sparkles, StickyNote, Upload, UserX, X } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const fields = [
  ['物件名','代沢レジデンス'], ['所在地','東京都世田谷区代沢5丁目18番12号'], ['地番','代沢五丁目124番8'],
  ['物件種別','一棟マンション'], ['売出価格','185,000,000'], ['想定利回り（%）',''],
  ['土地面積（㎡）','182.41'], ['建物延床面積（㎡）','365.22'], ['交通',''],
  ['地目','宅地'], ['権利','所有権'], ['構造','鉄筋コンクリート造4階建'],
  ['築年数','築11年'], ['用途地域','第一種中高層住居専用地域'], ['防火指定','準防火地域'],
  ['高度地区','第二種高度地区'], ['接道','南西側 公道 幅員5.4m'], ['その他制限','日影規制あり'],
];

export default function DesignUpload() {
  const [, setLocation] = useLocation();
  const [step, setStep] = useState<'upload'|'form'>('upload');
  const [visibility, setVisibility] = useState(false);
  const [notify, setNotify] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [publish, setPublish] = useState(true);
  const [hasFiles, setHasFiles] = useState(false);

  const analyze = () => { setAnalyzing(true); window.setTimeout(() => { setAnalyzing(false); setStep('form'); setVisibility(true); }, 700); };

  return <div className="min-h-screen bg-[#f2f5f8] pb-24 text-[#17211d]">
    {analyzing && <div className="fixed inset-0 z-50 grid place-items-center bg-white/90 px-5 backdrop-blur"><div className="w-full max-w-sm text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#e8eef6]"><Sparkles size={28} className="animate-pulse text-[#173f70]" /></div><h2 className="mt-5 text-[20px] font-bold text-[#102d50]">AI解析中</h2><p className="mt-2 text-[13px] text-[#65748a]">1件のPDFを解析しています…</p><div className="mt-5 bg-[#fff4df] px-4 py-3 text-[12px] font-semibold text-[#8a5b18]">完了するまでこのページから離れないでください</div></div></div>}

    <header className="sticky top-0 z-30 flex h-14 items-center border-b border-[#d9e0e8] bg-white px-3"><button onClick={() => step === 'form' ? setStep('upload') : setLocation('/design')} className="grid size-10 place-items-center"><ArrowLeft size={21} /></button><h1 className="ml-1 text-[17px] font-bold text-[#102d50]">物件情報の登録</h1></header>
    <div className="border-b border-[#d9e0e8] bg-white px-3 py-4"><div className="mx-auto flex max-w-3xl items-center"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#173f70] text-[11px] font-bold text-white">{step === 'form' ? <Check size={14} /> : 1}</span><span className="ml-1.5 whitespace-nowrap text-[10px] font-bold text-[#173f70]">資料アップロード</span><span className="mx-2 h-px flex-1 bg-[#cfd8e2]" /><span className={`grid size-7 shrink-0 place-items-center rounded-full text-[11px] font-bold ${step === 'form' ? 'bg-[#173f70] text-white' : 'bg-[#e5eaf0] text-[#718096]'}`}>2</span><span className={`ml-1.5 whitespace-nowrap text-[10px] font-bold ${step === 'form' ? 'text-[#173f70]' : 'text-[#7b8797]'}`}>内容確認</span><span className="mx-2 h-px flex-1 bg-[#cfd8e2]" /><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#e5eaf0] text-[11px] font-bold text-[#718096]">3</span><span className="ml-1.5 text-[10px] font-bold text-[#7b8797]">登録</span></div></div>

    <main className="mx-auto max-w-[1200px] lg:p-7">
      {step === 'upload' ? <section className="bg-white px-4 py-6"><h2 className="text-[21px] font-bold text-[#102d50]">物件資料をアップロード</h2><p className="mt-2 text-[13px] leading-6 text-[#65748a]">PDFまたは画像から、AIが物件情報を整理します。</p><button onClick={() => setHasFiles(true)} className="mt-6 flex h-40 w-full flex-col items-center justify-center border-2 border-dashed border-[#9cafc4] bg-[#f7f9fb] text-[#173f70]"><Upload size={29} /><span className="mt-3 text-[15px] font-bold">ファイルを選択</span><span className="mt-1 text-[11px] text-[#718096]">PDF・JPG・PNG／1ファイル20MBまで</span></button>{hasFiles && <div className="mt-4 flex items-center border border-[#dce3eb] p-3"><FileText size={20} className="text-[#c44848]" /><div className="ml-3 min-w-0 flex-1"><p className="truncate text-[13px] font-bold">代沢レジデンス_販売図面.pdf</p><p className="text-[10px] text-[#8490a0]">2.4 MB</p></div><button onClick={() => setHasFiles(false)}><X size={17} /></button></div>}<button onClick={() => hasFiles && analyze()} className={`mt-5 flex h-12 w-full items-center justify-center gap-2 text-[14px] font-bold ${hasFiles ? 'bg-[#173f70] text-white' : 'bg-[#dce2e8] text-[#8994a1]'}`}><Sparkles size={18} />AIで物件情報を読み取る</button><p className="mt-3 text-center text-[11px] text-[#758194]">複数の資料をまとめて読み取れます</p></section> : <div className="space-y-2">
        <section className="bg-white px-4 py-5"><div className="flex items-center justify-between"><div><h2 className="text-[19px] font-bold text-[#102d50]">内容確認・編集</h2><p className="mt-1 text-[12px] text-[#65748a]">AIの読み取り結果を確認してください。</p></div><span className="flex items-center gap-1 text-[11px] font-bold text-[#35724f]"><Check size={14} />解析完了</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(([label,value],i) => <label key={label} className={(i < 2 || i === 17) ? 'sm:col-span-2' : ''}><span className="text-[12px] font-semibold text-[#65748a]">{label}{i < 5 && <span className="ml-1 text-red-500">*</span>}</span><input defaultValue={value} placeholder="未入力" className="mt-1.5 h-11 w-full border border-[#cbd5df] px-3 text-[14px] outline-none focus:border-[#173f70]" /></label>)}</div></section>
        <section className="bg-white px-4 py-5"><h3 className="text-[16px] font-bold text-[#102d50]">商流・紹介コメント</h3><label className="mt-4 block"><span className="text-[12px] font-semibold text-[#65748a]">商流</span><input defaultValue="売主 → 元付 → 買主" className="mt-1.5 h-11 w-full border border-[#cbd5df] px-3 text-[14px]" /></label><textarea rows={4} defaultValue="世田谷区代沢の一棟マンションです。詳細は添付資料をご確認ください。" className="mt-4 w-full border border-[#cbd5df] p-3 text-[14px] leading-6" /><button className="mt-2 flex items-center gap-1 text-[12px] font-bold text-[#245f9d]"><Sparkles size={15} />AIで紹介コメントを作成</button></section>
        <section className="bg-white px-4 py-5"><h3 className="text-[16px] font-bold text-[#102d50]">登録資料</h3>{['代沢レジデンス_販売図面.pdf','登記簿謄本.pdf'].map((file,i) => <div key={file} className="mt-3 flex items-center border-b border-[#e2e7ec] pb-3"><FileText size={19} className="text-[#173f70]" /><span className="ml-3 min-w-0 flex-1 truncate text-[13px] font-bold">{file}</span><button className={`flex items-center gap-1 px-2 py-1.5 text-[10px] font-bold ${i ? 'bg-[#fff0dc] text-[#8c570f]' : 'bg-[#e9eef5] text-[#173f70]'}`}>{i ? <EyeOff size={13} /> : <Eye size={13} />}{i ? '登録者のみ' : '全員に公開'}</button></div>)}<button className="mt-3 flex items-center gap-2 text-[12px] font-bold text-[#173f70]"><Plus size={15} />追加資料をアップロード</button></section>
        <section className="bg-white px-4 py-5"><h3 className="flex items-center gap-2 text-[16px] font-bold text-[#102d50]"><Camera size={18} />現場写真 <span className="text-[11px] font-normal text-[#758194]">任意</span></h3><button className="mt-3 flex h-20 w-full items-center justify-center gap-2 border border-dashed border-[#9cafc4] text-[12px] font-bold text-[#173f70]"><Camera size={18} />写真を追加</button></section>
        <section className="bg-white px-4 py-5"><h3 className="flex items-center gap-2 text-[16px] font-bold text-[#102d50]"><StickyNote size={18} />自分専用メモ</h3><textarea rows={3} placeholder="他のユーザーには表示されません" className="mt-3 w-full border border-[#cbd5df] p-3 text-[14px]" /></section>
        <section className="bg-white px-4 py-5"><h3 className="flex items-center gap-2 text-[16px] font-bold text-[#102d50]"><HelpCircle size={18} />よくある質問</h3><button className="mt-3 flex h-11 w-full items-center justify-center gap-1 border border-dashed border-[#9cafc4] text-[12px] font-bold text-[#173f70]"><Plus size={15} />質問を追加</button></section>
        <section className="bg-white px-4 py-5"><h3 className="flex items-center gap-2 text-[16px] font-bold text-[#9b3030]"><UserX size={18} />閲覧制限</h3><p className="mt-1 text-[11px] text-[#758194]">設定したユーザーには物件が表示されません。</p><button className="mt-3 border border-[#cbd5df] px-3 py-2 text-[12px] font-bold text-[#173f70]">ユーザーを追加</button></section>
        <section className="bg-white px-4 py-5"><div className="grid grid-cols-2 gap-3"><button onClick={() => setPublish(true)} className={`p-3 text-left ${publish ? 'border-2 border-[#173f70] bg-[#edf3f9]' : 'border border-[#cbd5df]'}`}><Eye size={18} /><p className="mt-2 text-[13px] font-bold">今すぐ公開</p><p className="mt-1 text-[10px] text-[#65748a]">登録後すぐ閲覧可能</p></button><button onClick={() => setPublish(false)} className={`p-3 text-left ${!publish ? 'border-2 border-[#a36b19] bg-[#fff6e7]' : 'border border-[#cbd5df]'}`}><Lock size={18} /><p className="mt-2 text-[13px] font-bold">一時保存</p><p className="mt-1 text-[10px] text-[#65748a]">非公開で保存</p></button></div></section>
      </div>}
    </main>

    {step === 'form' && <footer className="fixed inset-x-0 bottom-0 z-30 border-t border-[#d8e0e8] bg-white p-3 pb-[max(12px,env(safe-area-inset-bottom))]"><div className="mx-auto flex max-w-3xl gap-3"><button onClick={() => setStep('upload')} className="h-12 flex-1 border border-[#173f70] text-[13px] font-bold text-[#173f70]">戻る</button><button onClick={() => publish ? setNotify(true) : (toast.success('下書き保存しました'), setLocation('/v2/preview/property'))} className="h-12 flex-[1.6] bg-[#173f70] text-[14px] font-bold text-white">{publish ? '今すぐ公開する' : '下書き保存する'}</button></div></footer>}

    {visibility && <div className="fixed inset-0 z-50 flex items-end bg-black/45 sm:items-center sm:justify-center" onClick={() => setVisibility(false)}><div className="w-full bg-white p-5 sm:max-w-sm" onClick={e => e.stopPropagation()}><h3 className="text-[18px] font-bold text-[#102d50]">企業情報が含まれている可能性があります</h3><p className="mt-2 text-[12px] leading-5 text-[#65748a]">ロゴや連絡先が含まれる資料の公開設定を選択してください。後から変更できます。</p><button onClick={() => setVisibility(false)} className="mt-5 h-11 w-full bg-[#173f70] text-[13px] font-bold text-white">全員に公開する</button><button onClick={() => setVisibility(false)} className="mt-2 h-11 w-full bg-[#fff0dc] text-[13px] font-bold text-[#8c570f]">非公開にする（登録者のみ）</button></div></div>}

    {notify && <div className="fixed inset-0 z-50 flex items-end bg-black/45 sm:items-center sm:justify-center sm:p-6"><div className="w-full bg-white p-5 sm:max-w-[520px] sm:border-t-4 sm:border-t-[#173f70] sm:p-7"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#e8eef6]"><Bell size={19} className="text-[#173f70]" /></div><div><p className="text-[12px] font-bold text-[#35724f]">物件を公開しました</p><h3 className="text-[18px] font-bold text-[#102d50] sm:text-[21px]">新着として通知しますか？</h3></div></div><div className="mt-5 grid gap-2 bg-[#f4f6f8] p-4 text-[13px] text-[#44546a] sm:grid-cols-3"><p>✓ 新着メール</p><p>✓ プッシュ通知</p><p>✓ LINE通知</p></div><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row"><button onClick={() => (toast.success('物件を公開しました'), setLocation('/v2/preview/property'))} className="h-11 flex-1 text-[12px] font-semibold text-[#65748a] sm:border sm:border-[#9aabc0]">通知しない</button><button onClick={() => (toast.success('物件を公開しました'), setLocation('/v2/preview/property'))} className="h-11 flex-[1.4] bg-[#173f70] text-[13px] font-bold text-white">通知して物件を見る</button></div></div></div>}
  </div>;
}
