import { Bell, Building2, ChevronRight, Eye, Heart, ListFilter, MessageCircle, Search, Sparkles, UserRound } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";

const listings = [
  { type: "一棟マンション", place: "代沢レジデンス", address: "東京都世田谷区代沢5丁目18番12号", price: "1億8,500万円", land: "182.41㎡", building: "365.22㎡", age: "築11年", match: 96, views: 32, talks: 4, time: "8月20日", badge: "新着・未読", accent: true },
  { type: "売地", place: "美しが丘四丁目 売地", address: "神奈川県横浜市青葉区美しが丘4丁目21番8号", price: "7,980万円", land: "247.80㎡", building: "—", age: "更地", match: 88, views: 18, talks: 2, time: "8月13日", badge: "", accent: false },
  { type: "中古戸建", place: "碑文谷五丁目 戸建", address: "東京都目黒区碑文谷5丁目14番3号", price: "1億2,300万円", land: "104.22㎡", building: "128.60㎡", age: "築7年", match: 81, views: 41, talks: 3, time: "8月5日", badge: "価格改定", accent: false },
  { type: "区分マンション", place: "白金台パークレジデンス 402", address: "東京都港区白金台3丁目7番15号", price: "9,850万円", land: "—", building: "72.18㎡", age: "築5年", match: 78, views: 12, talks: 1, time: "7月29日", badge: "", accent: false },
];

export default function NewDashboard() {
  const [, setLocation] = useLocation();
  const [filters, setFilters] = useState(false);
  const [searchMode, setSearchMode] = useState<'area' | 'keyword' | 'ai'>('area');
  const [region, setRegion] = useState<string | null>(null);
  return <div className="min-h-screen bg-white pb-20 text-[#17211d]">
    <header className="sticky top-0 z-30 border-b border-[#dfe3e1] bg-white/95 backdrop-blur">
      <div className="mx-auto flex h-14 max-w-3xl items-center px-4">
        <Building2 size={22} className="text-[#173f70]" /><span className="ml-2 text-[19px] font-bold tracking-tight text-[#102d50]">PropFlow</span>
        <button onClick={() => setLocation('/design/announcements')} aria-label="お知らせ" className="relative ml-auto grid size-10 place-items-center"><Bell size={19} /><span className="absolute right-2.5 top-2.5 size-1.5 rounded-full bg-red-500" /></button>
      </div>
    </header>

    <main className="mx-auto max-w-3xl">
      <section className="px-4 pb-4 pt-5">
        <div className="flex items-end justify-between"><div><p className="text-[13px] text-[#758194]">今週の新着 1件</p><h1 className="mt-1 text-[24px] font-bold text-[#102d50]">物件を探す</h1></div><button onClick={() => setFilters(true)} className="flex items-center gap-1.5 text-[13px] font-semibold text-[#173f70]"><ListFilter size={16} />絞り込み</button></div>
        <div className="mt-4 grid grid-cols-3 border border-[#cad3df] bg-[#f2f5f8] p-1">{[{id:'area',label:'エリア・条件'}, {id:'keyword',label:'キーワード'}, {id:'ai',label:'AI検索'}].map(mode => <button key={mode.id} onClick={() => setSearchMode(mode.id as typeof searchMode)} className={`flex h-9 items-center justify-center gap-1 text-[12px] font-bold ${searchMode === mode.id ? 'bg-white text-[#173f70] shadow-sm' : 'text-[#718096]'}`}>{mode.id === 'ai' && <Sparkles size={13} />}{mode.label}</button>)}</div>
        {searchMode === 'area' ? <div className="mt-2 border border-[#cad3df] bg-white p-3"><div className="flex flex-wrap gap-2">{['北海道・東北','関東','中部','近畿','中国・四国','九州・沖縄'].map(name => <button key={name} onClick={() => setRegion(region === name ? null : name)} className={`px-3 py-2 text-[12px] font-bold ${region === name ? 'bg-[#173f70] text-white' : 'border border-[#cbd5df] text-[#5f6e82]'}`}>{name}</button>)}</div>{region && <div className="mt-3 flex flex-wrap gap-2 border-t border-[#e1e6ec] pt-3">{(region === '関東' ? [['東京都',5],['神奈川県',2],['埼玉県',1]] : region === '近畿' ? [['大阪府',1],['京都府',1]] : [['該当物件なし',0]]).map(([name,count]) => <button key={name as string} disabled={!count} className={`px-3 py-2 text-[12px] font-bold ${count ? 'border border-[#9aabc0] text-[#173f70]' : 'text-[#9aa4af]'}`}>{name as string}{count ? `（${count}）` : ''}</button>)}</div>}<button onClick={() => setFilters(true)} className="mt-3 flex items-center gap-1.5 text-[12px] font-bold text-[#173f70]"><ListFilter size={15} />物件種別・価格・面積も指定</button></div> : <div className={`mt-2 flex h-12 items-center border bg-white px-3 ${searchMode === 'ai' ? 'border-[#789bc0]' : 'border-[#cad3df]'} focus-within:border-[#173f70]`}>{searchMode === 'ai' ? <Sparkles size={18} className="text-[#245f9d]" /> : <Search size={18} className="text-[#64748b]" />}<input className="ml-2 min-w-0 flex-1 border-0 bg-transparent text-[15px] outline-none" placeholder={searchMode === 'ai' ? '例：23区内、1億円以下の売地' : '物件名・地番・備考など'} />{searchMode === 'ai' ? <button className="ml-2 bg-[#173f70] px-3 py-2 text-[11px] font-bold text-white">検索</button> : <button onClick={() => setFilters(true)} aria-label="絞り込み" className="border-l border-[#dce3eb] pl-3 text-[#173f70]"><ListFilter size={18} /></button>}</div>}
        <div className="mt-3 flex gap-5 overflow-x-auto border-b border-[#dfe3e1] text-[13px] [scrollbar-width:none]">
          {['すべて', '未読', '注目', 'お気に入り'].map((label, i) => <button key={label} className={`shrink-0 border-b-2 pb-2.5 font-semibold ${i === 0 ? 'border-[#173f70] text-[#173f70]' : 'border-transparent text-[#758194]'}`}>{label}{i === 1 && <span className="ml-1 rounded-full bg-[#edf1f6] px-1.5 py-0.5 text-[9px]">1</span>}</button>)}
        </div>
      </section>

      <div className="flex items-center justify-between border-y border-[#e3e6e4] bg-[#f7f8f7] px-4 py-2.5 text-[12px] text-[#707a76]"><span><strong className="mr-1 text-[14px] text-[#102d50]">検索結果 8件</strong></span><button className="flex items-center gap-1">新着順 <ChevronRight size={14} className="rotate-90" /></button></div>

      <section className="bg-[#e8edf3]">
        {listings.map((item, index) => <article key={item.address} className={`relative bg-white px-4 py-4 active:bg-[#f7f8f7] ${index !== listings.length - 1 ? 'mb-2' : ''}`}>
          <span className={`absolute inset-y-0 left-0 w-[3px] ${item.accent ? 'bg-[#173f70]' : 'bg-transparent'}`} />
          <div className="flex items-center gap-2 text-[12px] font-semibold"><span className="text-[#5f6e82]">{item.type}</span>{item.badge && <span className={item.accent ? "bg-[#173f70] px-2 py-0.5 text-white" : "bg-[#e9eef5] px-2 py-0.5 text-[#43566f]"}>{item.badge}</span>}{item.talks >= 3 && <span className="bg-[#fff0dc] px-2 py-0.5 font-bold text-[#a45b00]">注目</span>}<span className="ml-auto text-[11px] text-[#8490a0]">{item.time}</span></div>
          <div className="mt-2 flex items-start gap-3"><button onClick={() => setLocation('/design/property')} className="min-w-0 flex-1 text-left"><h2 className="text-[17px] font-bold leading-snug text-[#17211d]">{item.place}</h2><p className="mt-1 text-[13px] leading-relaxed text-[#65748a]">{item.address}</p></button><div className="flex items-start gap-3"><p className="whitespace-nowrap text-[18px] font-bold">{item.price}</p><button aria-label="お気に入り"><Heart size={21} className="text-[#65716b]" /></button></div></div>
          <div className="mt-3 flex items-center gap-2 border-y border-[#edf0ee] py-2 text-[12px] font-semibold text-[#4f5f72]"><span>土地 {item.land}</span><span className="text-[#c1c8d0]">｜</span><span>建物 {item.building}</span><span className="text-[#c1c8d0]">｜</span><span>{item.age}</span></div>
          <div className="mt-3 flex items-center gap-4"><span className="flex items-center gap-1 text-[11px] font-semibold text-[#6f7d90]"><Eye size={15} />{item.views}回閲覧</span><div className="ml-auto flex items-center gap-4"><button onClick={() => setLocation('/design/chat')} className="flex items-center gap-1 text-[12px] font-bold text-[#173f70]"><MessageCircle size={15} />問い合わせ</button><button onClick={() => setLocation('/design/property')} aria-label="詳細を見る"><ChevronRight size={17} className="text-[#9ca8b7]" /></button></div></div>
        </article>)}
      </section>
    </main>

    {filters && <div className="fixed inset-0 z-50 flex items-end bg-black/45" onClick={() => setFilters(false)}><div className="max-h-[88vh] w-full overflow-y-auto bg-white" onClick={e => e.stopPropagation()}><div className="sticky top-0 flex items-center border-b border-[#dce3eb] bg-white px-4 py-4"><h2 className="text-[19px] font-bold text-[#102d50]">物件を絞り込む</h2><button onClick={() => setFilters(false)} className="ml-auto text-[13px] font-semibold text-[#65748a]">閉じる</button></div><div className="space-y-5 p-4"><label className="block"><span className="text-[13px] font-bold text-[#263b58]">所在地</span><div className="mt-2 grid grid-cols-2 gap-2"><select className="h-11 border border-[#cbd5df] px-3 text-[14px]"><option>都道府県すべて</option><option>東京都</option><option>神奈川県</option></select><input placeholder="市区町村・町名" className="h-11 border border-[#cbd5df] px-3 text-[14px]" /></div></label><div><p className="text-[13px] font-bold text-[#263b58]">物件種別</p><div className="mt-2 flex flex-wrap gap-2">{['土地','一棟マンション','区分マンション','一棟アパート','戸建','事務所ビル'].map((x,i) => <button key={x} className={`border px-3 py-2 text-[12px] font-semibold ${i === 1 ? 'border-[#173f70] bg-[#edf3f9] text-[#173f70]' : 'border-[#cbd5df] text-[#65748a]'}`}>{x}</button>)}</div></div><label className="block"><span className="text-[13px] font-bold text-[#263b58]">価格（万円）</span><div className="mt-2 flex items-center gap-2"><input placeholder="下限" inputMode="numeric" className="h-11 min-w-0 flex-1 border border-[#cbd5df] px-3 text-[14px]" /><span>〜</span><input placeholder="上限" inputMode="numeric" className="h-11 min-w-0 flex-1 border border-[#cbd5df] px-3 text-[14px]" /></div></label><label className="block"><span className="text-[13px] font-bold text-[#263b58]">土地面積（㎡）</span><div className="mt-2 flex items-center gap-2"><input placeholder="下限" inputMode="numeric" className="h-11 min-w-0 flex-1 border border-[#cbd5df] px-3 text-[14px]" /><span>〜</span><input placeholder="上限" inputMode="numeric" className="h-11 min-w-0 flex-1 border border-[#cbd5df] px-3 text-[14px]" /></div></label><div><p className="text-[13px] font-bold text-[#263b58]">状態</p><div className="mt-2 grid grid-cols-3 gap-2">{['未読のみ','注目のみ','公開中'].map(x => <label key={x} className="flex items-center border border-[#cbd5df] p-3 text-[12px] font-semibold"><input type="checkbox" className="mr-2" />{x}</label>)}</div></div></div><div className="sticky bottom-0 flex gap-3 border-t border-[#dce3eb] bg-white p-4"><button className="h-12 flex-1 border border-[#173f70] text-[13px] font-bold text-[#173f70]">クリア</button><button onClick={() => setFilters(false)} className="h-12 flex-[1.6] bg-[#173f70] text-[14px] font-bold text-white">8件を表示</button></div></div></div>}
    <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-[#dfe3e1] bg-white pb-[max(7px,env(safe-area-inset-bottom))] pt-2"><div className="mx-auto flex max-w-md items-end justify-around">
      <button onClick={() => setLocation('/design')} className="flex w-16 flex-col items-center gap-1 text-[10px] font-bold text-[#173f70]"><Search size={21} />物件一覧</button>
      <button onClick={() => setLocation('/design/favorites')} className="flex w-16 flex-col items-center gap-1 text-[10px] text-[#718096]"><Heart size={21} />お気に入り</button>
      <button onClick={() => setLocation('/design/messages')} className="relative flex w-16 flex-col items-center gap-1 text-[10px] text-[#718096]"><MessageCircle size={21} />DM<span className="absolute right-4 top-0 size-2 rounded-full bg-[#d84b4b] ring-2 ring-white" /></button>
      <button onClick={() => setLocation('/design/my-properties')} className="flex w-16 flex-col items-center gap-1 text-[10px] text-[#718096]"><Building2 size={21} />自社物件</button>
      <button onClick={() => setLocation('/design/mypage')} className="flex w-16 flex-col items-center gap-1 text-[10px] text-[#718096]"><UserRound size={21} />マイページ</button>
    </div></nav>
  </div>;
}
